2022-08-04 22:41:33,798 INFO    MainThread:16248 [wandb_setup.py:_flush():76] Configure stats pid to 16248
2022-08-04 22:41:33,798 INFO    MainThread:16248 [wandb_setup.py:_flush():76] Loading settings from C:\Users\rkaha\.config\wandb\settings
2022-08-04 22:41:33,798 INFO    MainThread:16248 [wandb_setup.py:_flush():76] Loading settings from C:\Users\rkaha\Documents\hopsworks\hopsworks-tutorials\nyc_taxi_fares\wandb\settings
2022-08-04 22:41:33,798 INFO    MainThread:16248 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'_require_service': 'True'}
2022-08-04 22:41:33,798 INFO    MainThread:16248 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-08-04 22:41:33,799 INFO    MainThread:16248 [wandb_init.py:_log_setup():461] Logging user logs to C:\Users\rkaha\Documents\hopsworks\hopsworks-tutorials\nyc_taxi_fares\wandb\run-20220804_224133-2cnxll0b\logs\debug.log
2022-08-04 22:41:33,799 INFO    MainThread:16248 [wandb_init.py:_log_setup():462] Logging internal logs to C:\Users\rkaha\Documents\hopsworks\hopsworks-tutorials\nyc_taxi_fares\wandb\run-20220804_224133-2cnxll0b\logs\debug-internal.log
2022-08-04 22:41:33,800 INFO    MainThread:16248 [wandb_init.py:init():495] calling init triggers
2022-08-04 22:41:33,800 INFO    MainThread:16248 [wandb_init.py:init():498] wandb.init called with sweep_config: {}
config: {}
2022-08-04 22:41:33,800 INFO    MainThread:16248 [wandb_init.py:init():514] re-initializing run, found existing run on stack: 1knjl0xn
2022-08-04 22:41:33,804 INFO    MainThread:16248 [wandb_run.py:_finish():1727] finishing run rktraz_/nyc_taxi_fares/1knjl0xn
2022-08-04 22:41:33,806 INFO    MainThread:16248 [jupyter.py:save_history():435] not saving jupyter history
2022-08-04 22:41:33,806 INFO    MainThread:16248 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2022-08-04 22:41:33,806 INFO    MainThread:16248 [wandb_init.py:_jupyter_teardown():393] cleaning up jupyter logic
2022-08-04 22:41:33,807 INFO    MainThread:16248 [wandb_run.py:_atexit_cleanup():1930] got exitcode: 0
2022-08-04 22:41:33,808 INFO    MainThread:16248 [wandb_run.py:_restore():1913] restore
2022-08-04 22:41:33,808 INFO    MainThread:16248 [wandb_run.py:_restore():1919] restore done
2022-08-04 22:41:33,819 INFO    MainThread:16248 [wandb_run.py:_on_finish():2220] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 779
  total_bytes: 779
}

2022-08-04 22:41:34,168 INFO    MainThread:16248 [wandb_run.py:_on_finish():2220] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 779
  total_bytes: 779
}

2022-08-04 22:41:37,700 INFO    MainThread:16248 [wandb_run.py:_on_finish():2220] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 779
  total_bytes: 779
}

2022-08-04 22:41:38,305 INFO    MainThread:16248 [wandb_run.py:_on_finish():2220] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 779
  total_bytes: 32722
}

2022-08-04 22:41:38,413 INFO    MainThread:16248 [wandb_run.py:_on_finish():2220] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 779
  total_bytes: 32722
}

2022-08-04 22:41:38,520 INFO    MainThread:16248 [wandb_run.py:_on_finish():2220] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 779
  total_bytes: 32722
}

2022-08-04 22:41:38,628 INFO    MainThread:16248 [wandb_run.py:_on_finish():2220] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 32722
  total_bytes: 32722
}

2022-08-04 22:41:38,746 INFO    MainThread:16248 [wandb_run.py:_on_finish():2220] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 32722
  total_bytes: 32722
}

2022-08-04 22:41:38,851 INFO    MainThread:16248 [wandb_run.py:_on_finish():2220] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 32722
  total_bytes: 32722
}

2022-08-04 22:41:38,962 INFO    MainThread:16248 [wandb_run.py:_on_finish():2220] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 32722
  total_bytes: 32722
}

2022-08-04 22:41:39,069 INFO    MainThread:16248 [wandb_run.py:_on_finish():2220] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 32722
  total_bytes: 32722
}

2022-08-04 22:41:39,179 INFO    MainThread:16248 [wandb_run.py:_on_finish():2220] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 32722
  total_bytes: 32722
}

2022-08-04 22:41:39,723 INFO    MainThread:16248 [wandb_run.py:_on_finish():2220] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 32722
  total_bytes: 32722
}

2022-08-04 22:41:40,053 INFO    MainThread:16248 [wandb_run.py:_on_finish():2220] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 32722
  total_bytes: 32722
}
local_info {
}

2022-08-04 22:41:41,174 INFO    MainThread:16248 [wandb_run.py:_footer_history_summary_info():3304] rendering history
2022-08-04 22:41:41,175 INFO    MainThread:16248 [wandb_run.py:_footer_history_summary_info():3336] rendering summary
2022-08-04 22:41:41,189 INFO    MainThread:16248 [wandb_run.py:_footer_sync_info():3260] logging synced files
2022-08-04 22:41:41,212 INFO    MainThread:16248 [wandb_init.py:init():548] starting backend
2022-08-04 22:41:41,212 INFO    MainThread:16248 [wandb_init.py:init():552] setting up manager
2022-08-04 22:41:41,222 INFO    MainThread:16248 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2022-08-04 22:41:41,230 INFO    MainThread:16248 [wandb_init.py:init():558] backend started and connected
2022-08-04 22:41:41,260 INFO    MainThread:16248 [wandb_run.py:_label_probe_notebook():1105] probe notebook
2022-08-04 22:41:41,261 INFO    MainThread:16248 [wandb_run.py:_label_probe_notebook():1115] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-08-04 22:41:41,261 INFO    MainThread:16248 [wandb_init.py:init():636] updated telemetry
2022-08-04 22:41:41,540 INFO    MainThread:16248 [wandb_init.py:init():667] communicating run to backend with 30 second timeout
2022-08-04 22:41:42,664 INFO    MainThread:16248 [wandb_run.py:_on_init():1981] communicating current version
2022-08-04 22:41:42,826 INFO    MainThread:16248 [wandb_run.py:_on_init():1985] got version response 
2022-08-04 22:41:42,826 INFO    MainThread:16248 [wandb_init.py:init():700] starting run threads in backend
2022-08-04 22:41:43,050 INFO    MainThread:16248 [wandb_run.py:_console_start():1961] atexit reg
2022-08-04 22:41:43,050 INFO    MainThread:16248 [wandb_run.py:_redirect():1819] redirect: SettingsConsole.WRAP_RAW
2022-08-04 22:41:43,051 INFO    MainThread:16248 [wandb_run.py:_redirect():1884] Wrapping output streams.
2022-08-04 22:41:43,051 INFO    MainThread:16248 [wandb_run.py:_redirect():1906] Redirects installed.
2022-08-04 22:41:43,052 INFO    MainThread:16248 [wandb_init.py:init():732] run started, returning control to user process
2022-08-04 22:42:19,404 WARNING MsgRouterThr:16248 [router.py:message_loop():76] message_loop has been closed
